{"name": "Test to verify that user can complete the job with exception when task are paused and completed with exception ", "status": "skipped", "statusDetails": {"message": "Skipped: We cannot complete the job with exception when task are paused", "trace": "('/home/server1/Downloads/platform-api-develop/tests/scenarios/job/test_job_execution.py', 1446, 'Skipped: We cannot complete the job with exception when task are paused')"}, "description": "This testcase tests completing job with exception when task are paused and completed with exception", "parameters": [{"name": "job_execution_by", "value": "'user_group'"}, {"name": "users_list", "value": "[]"}], "start": 1733499021680, "stop": 1733499021680, "uuid": "468a4faf-b1ad-4991-baf6-159e7b30396c", "historyId": "9376c4925c67262c8775517fd5b5f718", "testCaseId": "10eda948fa7f467631c4aa8e7c79a110", "fullName": "tests.scenarios.job.test_job_execution.TestJobExecution#test_complete_job_having_pause_task_with_exception", "labels": [{"name": "tag", "value": "@pytest.mark.skip(reason='We cannot complete the job with exception when task are paused')"}, {"name": "tag", "value": "complete_job_having_pause_task_with_exception"}, {"name": "tag", "value": "job"}, {"name": "tag", "value": "scenario"}, {"name": "parentSuite", "value": "tests.scenarios.job"}, {"name": "suite", "value": "test_job_execution"}, {"name": "subSuite", "value": "TestJobExecution"}, {"name": "host", "value": "ubuntu"}, {"name": "thread", "value": "29333-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.scenarios.job.test_job_execution"}], "links": [{"type": "link", "url": "https://app.clickup.com/t/86cukrh1m", "name": "https://app.clickup.com/t/86cukrh1m"}]}