{"name": "Test to verify that user can complete the job with exception when task are paused and completed with exception ", "status": "skipped", "statusDetails": {"message": "Skipped: We cannot complete the job with exception when task are paused", "trace": "('/home/server1/Downloads/platform-api-develop/tests/scenarios/job/test_job_execution.py', 1446, 'Skipped: We cannot complete the job with exception when task are paused')"}, "description": "This testcase tests completing job with exception when task are paused and completed with exception", "parameters": [{"name": "job_execution_by", "value": "'user'"}, {"name": "users_list", "value": "['process.publisher.03']"}], "start": 1733761294065, "stop": 1733761294065, "uuid": "07be46d7-643a-444d-a0c7-8facdd417911", "historyId": "5c14922ac08221d1d2ff967e8c36f4a6", "testCaseId": "10eda948fa7f467631c4aa8e7c79a110", "fullName": "tests.scenarios.job.test_job_execution.TestJobExecution#test_complete_job_having_pause_task_with_exception", "labels": [{"name": "tag", "value": "@pytest.mark.skip(reason='We cannot complete the job with exception when task are paused')"}, {"name": "tag", "value": "complete_job_having_pause_task_with_exception"}, {"name": "tag", "value": "job"}, {"name": "tag", "value": "scenario"}, {"name": "parentSuite", "value": "tests.scenarios.job"}, {"name": "suite", "value": "test_job_execution"}, {"name": "subSuite", "value": "TestJobExecution"}, {"name": "host", "value": "ubuntu"}, {"name": "thread", "value": "53959-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.scenarios.job.test_job_execution"}], "links": [{"type": "link", "url": "https://app.clickup.com/t/86cukrh1m", "name": "https://app.clickup.com/t/86cukrh1m"}]}