{"name": "Test to verify that user can complete the task with exception when recurrence is configured", "status": "passed", "description": "This test is to verify the user can complete the task with exception when recurrence is configured", "parameters": [{"name": "job_execution_by", "value": "'user'"}, {"name": "users_list", "value": "['process.publisher.03']"}], "start": 1733501096104, "stop": 1733501105599, "uuid": "62c0cbfc-b270-45c4-99af-b7c1c4bad8d4", "historyId": "b6decb3ec0be7ffe1b02080c445dae24", "testCaseId": "2a539fb0f9faa0f7ca3090583714cf1f", "fullName": "tests.scenarios.job.test_recurrence_execution.TestRecurrenceExecution#test_task_completion_with_exception_when_recurrence_configured", "labels": [{"name": "tag", "value": "test_task_completion_with_exception_when_recurrence_configured"}, {"name": "tag", "value": "task_recurrence_execution"}, {"name": "tag", "value": "job"}, {"name": "tag", "value": "scenario"}, {"name": "tag", "value": "recurrence"}, {"name": "parentSuite", "value": "tests.scenarios.job"}, {"name": "suite", "value": "test_recurrence_execution"}, {"name": "subSuite", "value": "TestRecurrenceExecution"}, {"name": "host", "value": "ubuntu"}, {"name": "thread", "value": "29333-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.scenarios.job.test_recurrence_execution"}], "links": [{"type": "link", "url": "https://app.clickup.com/t/86cvx843e", "name": "https://app.clickup.com/t/86cvx843e"}]}