{"name": "Test to validate error while creating user group with existing group name", "status": "passed", "description": "This testcase test error while creating user group with existing group name", "start": 1733768305086, "stop": 1733768306189, "uuid": "47df481e-4c90-4688-a54a-3185a96c661c", "historyId": "9ea1add521e5e469284421b705bcac50", "testCaseId": "14d42ee5aa4f4c617f9f4d1b016efd3d", "fullName": "tests.scenarios.user_and_access.test_user_groups.TestUserGroups#test_validate_user_group_creation_with_existing_group_name", "labels": [{"name": "tag", "value": "validate_user_group_creation_with_existing_group_name"}, {"name": "tag", "value": "user_and_access"}, {"name": "tag", "value": "scenario"}, {"name": "parentSuite", "value": "tests.scenarios.user_and_access"}, {"name": "suite", "value": "test_user_groups"}, {"name": "subSuite", "value": "TestUserGroups"}, {"name": "host", "value": "ubuntu"}, {"name": "thread", "value": "53959-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.scenarios.user_and_access.test_user_groups"}], "links": [{"type": "link", "url": "https://app.clickup.com/t/86cuw4wwg", "name": "https://app.clickup.com/t/86cuw4wwg"}]}