{"name": "Test to verify that user can complete the task with exception when recurrence is configured", "status": "passed", "description": "This test is to verify the user can complete the task with exception when recurrence is configured", "parameters": [{"name": "job_execution_by", "value": "'user_group'"}, {"name": "users_list", "value": "[]"}], "start": 1733763621751, "stop": 1733763632569, "uuid": "20ec40be-30df-4360-9b9b-bbb2c70c52e1", "historyId": "83653f49684183e26873cffa099a7109", "testCaseId": "2a539fb0f9faa0f7ca3090583714cf1f", "fullName": "tests.scenarios.job.test_recurrence_execution.TestRecurrenceExecution#test_task_completion_with_exception_when_recurrence_configured", "labels": [{"name": "tag", "value": "test_task_completion_with_exception_when_recurrence_configured"}, {"name": "tag", "value": "task_recurrence_execution"}, {"name": "tag", "value": "job"}, {"name": "tag", "value": "scenario"}, {"name": "tag", "value": "recurrence"}, {"name": "parentSuite", "value": "tests.scenarios.job"}, {"name": "suite", "value": "test_recurrence_execution"}, {"name": "subSuite", "value": "TestRecurrenceExecution"}, {"name": "host", "value": "ubuntu"}, {"name": "thread", "value": "53959-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.scenarios.job.test_recurrence_execution"}], "links": [{"type": "link", "url": "https://app.clickup.com/t/86cvx843e", "name": "https://app.clickup.com/t/86cvx843e"}]}