{"name": "Test to validate error while updating user group name with some existing group name", "status": "passed", "description": "This testcase test error while updating user group name with some existing group name", "start": 1733768310176, "stop": 1733768311827, "uuid": "8fdd1daf-6349-465c-b44a-17dce06d944d", "historyId": "8dd353d6c0947bd4b91b836d0e3dc206", "testCaseId": "463f5d762ec3b8eed7f2ce026dba86fb", "fullName": "tests.scenarios.user_and_access.test_user_groups.TestUserGroups#test_validate_user_group_name_update_with_existing_group_name", "labels": [{"name": "tag", "value": "validate_user_group_name_update_with_existing_group_name"}, {"name": "tag", "value": "user_and_access"}, {"name": "tag", "value": "scenario"}, {"name": "parentSuite", "value": "tests.scenarios.user_and_access"}, {"name": "suite", "value": "test_user_groups"}, {"name": "subSuite", "value": "TestUserGroups"}, {"name": "host", "value": "ubuntu"}, {"name": "thread", "value": "53959-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.scenarios.user_and_access.test_user_groups"}], "links": [{"type": "link", "url": "https://app.clickup.com/t/86cuw4wzd", "name": "https://app.clickup.com/t/86cuw4wzd"}]}