{"name": "Test to validate the error when user tries to start the task having task executor lock enabled just after completing has executor task", "status": "passed", "description": "This test case tests the error when user tries to start the task having task executor lock enabled after completing has executor task ", "parameters": [{"name": "job_execution_by", "value": "'user'"}, {"name": "users_list", "value": "['process.publisher.03', 'process.publisher.04']"}], "start": 1733504821442, "stop": 1733504832250, "uuid": "48bf8d33-757b-4843-88f1-c17abb21ef79", "historyId": "66bd0ee98e7693c30e9805201366421b", "testCaseId": "f4b96da938a1cffc7ba7ab6e456800d1", "fullName": "tests.scenarios.job.test_task_executor_lock_execution.TestTaskExecutorLockExecution#test_start_task_after_completing_has_executor_task", "labels": [{"name": "tag", "value": "start_task_after_completing_has_executor_task"}, {"name": "tag", "value": "job"}, {"name": "tag", "value": "scenario"}, {"name": "parentSuite", "value": "tests.scenarios.job"}, {"name": "suite", "value": "test_task_executor_lock_execution"}, {"name": "subSuite", "value": "TestTaskExecutorLockExecution"}, {"name": "host", "value": "ubuntu"}, {"name": "thread", "value": "29333-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.scenarios.job.test_task_executor_lock_execution"}], "links": [{"type": "link", "url": "https://app.clickup.com/t/86cv4ekqc", "name": "https://app.clickup.com/t/86cv4ekqc"}]}