{"name": "Test to verify that user gets expected error message when trying to complete task having interlocks with date-time property and task completed trigger", "status": "passed", "description": "This test case tests that the user gets expected error message when trying to complete task having interlocks with date-time property and task completed trigger", "parameters": [{"name": "job_execution_by", "value": "'user'"}, {"name": "users_list", "value": "['process.publisher.03']"}], "start": 1733497422975, "stop": 1733497445300, "uuid": "bd0af54d-ed0e-46c3-a288-3ba64d1b16c0", "historyId": "61525d4ab0d285f0e8c80642204be2d5", "testCaseId": "58f24113cf419b93a5e12fabd3dad973", "fullName": "tests.scenarios.job.test_interlocks_execution.TestInterlocksExecution#test_validate_expected_error_while_execution_of_task_interlocks_with_date_time_property_and_task_completed_trigger", "labels": [{"name": "tag", "value": "validate_expected_error_while_execution_of_task_interlocks_with_date_time_property_and_task_completed_trigger"}, {"name": "tag", "value": "interlocks"}, {"name": "tag", "value": "job"}, {"name": "tag", "value": "scenario"}, {"name": "parentSuite", "value": "tests.scenarios.job"}, {"name": "suite", "value": "test_interlocks_execution"}, {"name": "subSuite", "value": "TestInterlocksExecution"}, {"name": "host", "value": "ubuntu"}, {"name": "thread", "value": "29333-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.scenarios.job.test_interlocks_execution"}], "links": [{"type": "link", "url": "https://app.clickup.com/t/86cur1yg4", "name": "https://app.clickup.com/t/86cur1yg4"}]}