{"name": "Test to verify that user can initiate the exception approval workflow for number parameter with resource type validation", "status": "failed", "statusDetails": {"message": "AssertionError", "trace": "self = <test_resource_parameter_exception_management_execution.TestResourceParameterExceptionManagementExecution object at 0x7af8220913a0>\nuser_group_creation = 'Auto_Test_user_group_TestResourceParameterExceptionManagementExecution_1836', job_execution_by = 'user_group', users_list = []\n\n    @allure.title(\n        \"Test to verify that user can initiate the exception approval workflow for number parameter with resource \"\n        \"type validation\")\n    @allure.description(\n        \"This test case validates that user can initiate the exception approval workflow for number parameter with \"\n        \"resource type validation with constant value\")\n    @allure.link(\"https://app.clickup.com/t/86cvhj4dg\")\n    @pytest.mark.scenario\n    @pytest.mark.job\n    @pytest.mark.exception_management_workflow\n    @pytest.mark.validate_exception_approval_workflow_on_resource_type_validation_with_constant_value\n    @pytest.mark.parametrize(\"job_execution_by, users_list\", [\n        (\"user\", [Env.get_env_data(\"QA_PUBLISHER_USERNAME_01\"), Env.get_env_data(\"QA_PUBLISHER_USERNAME_02\")]),\n        (\"user_group\", [])])\n    def test_validate_exception_approval_workflow_on_resource_type_validation_with_constant_value(self,\n                                                                                                  user_group_creation,\n                                                                                                  job_execution_by,\n                                                                                                  users_list):\n>       process_data = self.process_obj.test_add_number_parameter_with_resource_type_validation_enabled_approval_flow_exception_workflow()\n\ntests/scenarios/job/test_resource_parameter_exception_management_execution.py:56: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \ntests/scenarios/test_number_parameter_exception_management.py:145: in test_add_number_parameter_with_resource_type_validation_enabled_approval_flow_exception_workflow\n    validate_checklist()\ntests/unit/prototyping/process.py:186: in validate_checklist\n    status_200(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nresponse = <Response [500]>, message = ''\n\n    def status_200(response, message=None):\n        if message is None:\n            message = response.text\n>       assert response.status_code == 200, message\nE       AssertionError\n\nutil/validate_response.py:4: AssertionError"}, "description": "This test case validates that user can initiate the exception approval workflow for number parameter with resource type validation with constant value", "parameters": [{"name": "job_execution_by", "value": "'user_group'"}, {"name": "users_list", "value": "[]"}], "start": 1733501637382, "stop": 1733501644348, "uuid": "9fb577bd-1162-4983-890b-8174a2dc3665", "historyId": "d1d6ab10d20836afe1bb9fc445eae464", "testCaseId": "d54880c87bd669d4eef555911c196605", "fullName": "tests.scenarios.job.test_resource_parameter_exception_management_execution.TestResourceParameterExceptionManagementExecution#test_validate_exception_approval_workflow_on_resource_type_validation_with_constant_value", "labels": [{"name": "tag", "value": "validate_exception_approval_workflow_on_resource_type_validation_with_constant_value"}, {"name": "tag", "value": "exception_management_workflow"}, {"name": "tag", "value": "job"}, {"name": "tag", "value": "scenario"}, {"name": "parentSuite", "value": "tests.scenarios.job"}, {"name": "suite", "value": "test_resource_parameter_exception_management_execution"}, {"name": "subSuite", "value": "TestResourceParameterExceptionManagementExecution"}, {"name": "host", "value": "ubuntu"}, {"name": "thread", "value": "29333-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.scenarios.job.test_resource_parameter_exception_management_execution"}], "links": [{"type": "link", "url": "https://app.clickup.com/t/86cvhj4dg", "name": "https://app.clickup.com/t/86cvhj4dg"}]}