{"name": "Test to verify that user can configure number parameter with criteria type validation, in between condition, enabled reasoned entry and constant value", "status": "failed", "statusDetails": {"message": "AssertionError", "trace": "self = <test_number_parameter_exception_management.TestNumberParameterExceptionManagement object at 0x7af82273d6d0>\n\n    @allure.title(\n        \"Test to verify that user can configure number parameter with criteria type validation, in between condition, \"\n        \"enabled reasoned entry and constant value\")\n    @allure.description(\n        \"This test case tests adding number parameter with criteria type validation, in between condition, \"\n        \"enabled reasoned entry and constant value\")\n    @allure.link(\"https://app.clickup.com/t/86cvmvntm\")\n    @pytest.mark.scenario\n    @pytest.mark.create_prototype\n    @pytest.mark.exception_management_workflow\n    @pytest.mark.add_number_parameter_with_criteria_type_validation_in_between_condition_enabled_reasoned_entry_and_constant_values\n    def test_add_number_parameter_with_criteria_type_validation_in_between_condition_enabled_reasoned_entry_and_constant_values(\n            self):\n        checklist_name_01 = self.test_add_number_parameter_with_criteria_type_validation_in_between_condition_enabled_reasoned_entry_and_constant_values.__name__\n        login(Env.get_env_data(\"QA_ADMIN_USERNAME_01\"), Env.get_env_data(\"QA_ADMIN_PASSWORD_01\"))\n        select_facility(const.FACILITY_NAME)\n        select_usecase(const.USECASE_NAME)\n    \n        create_new_checklist(checklist_name_01, const.USECASE_ID, const.FACILITY_ID)\n        add_stage(stage_name_01)\n        add_task(stage_name_01, task_name_01)\n        defined_error = \"Error - validation failed for criteria type validation\"\n    \n        number_param = get_parameter_data(\"number\")\n        add_number_parameter(stage_name_01, task_name_01, number_param,\n                             validations=[\n                                 {\"Validation_type\": \"criteria\", \"criteria\": \"constant\", \"operator\": \"-\",\n                                  \"error\": defined_error, \"lower_value\": \"10\", \"upper_value\": \"20\"}],\n                             enable_exception_approval=\"ACCEPT_WITH_REASON_FLOW\")\n>       validate_checklist()\n\ntests/scenarios/test_number_parameter_exception_management.py:461: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \ntests/unit/prototyping/process.py:186: in validate_checklist\n    status_200(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nresponse = <Response [500]>, message = ''\n\n    def status_200(response, message=None):\n        if message is None:\n            message = response.text\n>       assert response.status_code == 200, message\nE       AssertionError\n\nutil/validate_response.py:4: AssertionError"}, "description": "This test case tests adding number parameter with criteria type validation, in between condition, enabled reasoned entry and constant value", "start": 1733492227154, "stop": 1733492228265, "uuid": "6e89bce2-0818-4904-a99d-6f2cb2d95f98", "historyId": "e2445765165af85a98ff837f3aeba75c", "testCaseId": "3ca1703413ea5ad77d6affaa6d4ff228", "fullName": "tests.scenarios.test_number_parameter_exception_management.TestNumberParameterExceptionManagement#test_add_number_parameter_with_criteria_type_validation_in_between_condition_enabled_reasoned_entry_and_constant_values", "labels": [{"name": "tag", "value": "add_number_parameter_with_criteria_type_validation_in_between_condition_enabled_reasoned_entry_and_constant_values"}, {"name": "tag", "value": "exception_management_workflow"}, {"name": "tag", "value": "create_prototype"}, {"name": "tag", "value": "scenario"}, {"name": "parentSuite", "value": "tests.scenarios"}, {"name": "suite", "value": "test_number_parameter_exception_management"}, {"name": "subSuite", "value": "TestNumberParameterExceptionManagement"}, {"name": "host", "value": "ubuntu"}, {"name": "thread", "value": "29333-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.scenarios.test_number_parameter_exception_management"}], "links": [{"type": "link", "url": "https://app.clickup.com/t/86cvmvntm", "name": "https://app.clickup.com/t/86cvmvntm"}]}