{"name": "Test to verify that user gets expected error message when trying to complete task having interlocks with number property and task completed trigger", "status": "passed", "description": "This test case tests that the user gets expected error message when trying to complete task having interlocks with number property and task completed trigger", "parameters": [{"name": "job_execution_by", "value": "'user_group'"}, {"name": "users_list", "value": "[]"}], "start": 1733496837107, "stop": 1733496877013, "uuid": "79a52d4d-aa8d-4a05-8bc4-fc0830c59607", "historyId": "c48151548808034d83127e0f701d4f1b", "testCaseId": "5c7d265ede6c432138a633abb5dd12e4", "fullName": "tests.scenarios.job.test_interlocks_execution.TestInterlocksExecution#test_validate_expected_error_while_execution_of_task_interlocks_with_number_property_and_task_completed_trigger", "labels": [{"name": "tag", "value": "validate_expected_error_while_execution_of_task_interlocks_with_number_property_and_task_completed_trigger"}, {"name": "tag", "value": "interlocks"}, {"name": "tag", "value": "job"}, {"name": "tag", "value": "scenario"}, {"name": "parentSuite", "value": "tests.scenarios.job"}, {"name": "suite", "value": "test_interlocks_execution"}, {"name": "subSuite", "value": "TestInterlocksExecution"}, {"name": "host", "value": "ubuntu"}, {"name": "thread", "value": "29333-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.scenarios.job.test_interlocks_execution"}], "links": [{"type": "link", "url": "https://app.clickup.com/t/86cuqtkyg", "name": "https://app.clickup.com/t/86cuqtkyg"}]}