{"name": "Test to verify that user gets expected error message when trying to complete task having interlocks with number property and task completed trigger", "status": "passed", "description": "This test case tests that the user gets expected error message when trying to complete task having interlocks with number property and task completed trigger", "parameters": [{"name": "job_execution_by", "value": "'user'"}, {"name": "users_list", "value": "['process.publisher.03']"}], "start": 1733758998447, "stop": 1733759029100, "uuid": "9e0dbfa9-d266-4f03-a9a1-5b9b74e9b875", "historyId": "5c97c78cb46512b221b483f0f1216ae9", "testCaseId": "5c7d265ede6c432138a633abb5dd12e4", "fullName": "tests.scenarios.job.test_interlocks_execution.TestInterlocksExecution#test_validate_expected_error_while_execution_of_task_interlocks_with_number_property_and_task_completed_trigger", "labels": [{"name": "tag", "value": "validate_expected_error_while_execution_of_task_interlocks_with_number_property_and_task_completed_trigger"}, {"name": "tag", "value": "interlocks"}, {"name": "tag", "value": "job"}, {"name": "tag", "value": "scenario"}, {"name": "parentSuite", "value": "tests.scenarios.job"}, {"name": "suite", "value": "test_interlocks_execution"}, {"name": "subSuite", "value": "TestInterlocksExecution"}, {"name": "host", "value": "ubuntu"}, {"name": "thread", "value": "53959-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.scenarios.job.test_interlocks_execution"}], "links": [{"type": "link", "url": "https://app.clickup.com/t/86cuqtkyg", "name": "https://app.clickup.com/t/86cuqtkyg"}]}