{"name": "Test to verify that user gets expected error message when trying to complete task having interlocks with all allowed property and task completed trigger", "status": "passed", "description": "This test case tests that the user gets expected error message when trying to complete task having interlocks with all allowed property and task completed trigger", "parameters": [{"name": "job_execution_by", "value": "'user'"}, {"name": "users_list", "value": "['process.publisher.03']"}], "start": 1733497657429, "stop": 1733497678392, "uuid": "b6313599-9d92-44dc-a15b-4c6e355af3ec", "historyId": "ea3512cc013f9246f2ce939dd76c26e4", "testCaseId": "c89dfe2f9a439a4cf9a262329dced774", "fullName": "tests.scenarios.job.test_interlocks_execution.TestInterlocksExecution#test_validate_expected_error_while_execution_of_task_interlocks_with_all_allowed_property_and_task_completed_trigger", "labels": [{"name": "tag", "value": "validate_expected_error_while_execution_of_task_interlocks_with_all_allowed_property_and_task_completed_trigger"}, {"name": "tag", "value": "interlocks"}, {"name": "tag", "value": "job"}, {"name": "tag", "value": "scenario"}, {"name": "parentSuite", "value": "tests.scenarios.job"}, {"name": "suite", "value": "test_interlocks_execution"}, {"name": "subSuite", "value": "TestInterlocksExecution"}, {"name": "host", "value": "ubuntu"}, {"name": "thread", "value": "29333-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.scenarios.job.test_interlocks_execution"}], "links": [{"type": "link", "url": "https://app.clickup.com/t/86curqa77", "name": "https://app.clickup.com/t/86curqa77"}]}