{"name": "Test to verify that user gets expected error message when trying to complete task having interlocks with number property and task start trigger", "status": "passed", "description": "This test case tests that the user gets expected error message when trying to complete task having interlocks with number property and task start trigger", "parameters": [{"name": "job_execution_by", "value": "'user_group'"}, {"name": "users_list", "value": "[]"}], "start": 1733759147933, "stop": 1733759172419, "uuid": "8c6612bf-5832-444a-97d6-1433ae0378e6", "historyId": "28247c1acee87d11026bf887e11b6953", "testCaseId": "d6d13a6b0631c945ea9544ea1f0377ae", "fullName": "tests.scenarios.job.test_interlocks_execution.TestInterlocksExecution#test_validate_expected_error_while_execution_of_task_interlocks_with_number_property_and_task_start_trigger", "labels": [{"name": "tag", "value": "validate_expected_error_while_execution_of_task_interlocks_with_number_property_and_task_start_trigger"}, {"name": "tag", "value": "interlocks"}, {"name": "tag", "value": "job"}, {"name": "tag", "value": "scenario"}, {"name": "parentSuite", "value": "tests.scenarios.job"}, {"name": "suite", "value": "test_interlocks_execution"}, {"name": "subSuite", "value": "TestInterlocksExecution"}, {"name": "host", "value": "ubuntu"}, {"name": "thread", "value": "53959-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.scenarios.job.test_interlocks_execution"}], "links": [{"type": "link", "url": "https://app.clickup.com/t/86cuqu1q9", "name": "https://app.clickup.com/t/86cuqu1q9"}]}